"""Raw extracted creativity / homogenization estimates from subagent sweep.

128 outcomes from 8 papers (RCT and Hybrid designs only).
5 paywalled stubs (Moon-G-K, Meincke-N-T, Lee, Boussioux, Girotra) still need full PDFs.

Metric heterogeneity is intentional — different studies report different units:
  - cohens_d: standardized effect size (best for meta-analysis)
  - raw_mean: OLS coefficient or raw mean difference (units of original outcome)
  - pairwise_cosine: cosine similarity (homogenization metric, units ∈ [0,1])
  - rouge / bleu / bertscore: corpus-level similarity metrics
  - distinct_n: lexical diversity (unique-n-gram fraction)
  - other: paper-specific metrics (Cliff's delta, perplexity, etc.)

Schema fields:
  paper_key, outcome_idx, outcome_name, treatment, control, outcome_var,
  metric_type, effect, se, ci_lo, ci_hi, n, direction, outcome_type

Direction conventions:
  +1 = AI helps creativity / heterogenizes
  -1 = AI hurts creativity / homogenizes
   0 = mixed / null
"""

def _e(paper_key, idx, name, treatment, control, outcome_var,
       metric_type, effect, se=None, ci_lo=None, ci_hi=None,
       n=None, direction=0, outcome_type="individual_creativity", notes=""):
    return dict(
        paper_key=paper_key, outcome_idx=idx, outcome_name=name,
        treatment=treatment, control=control, outcome_var=outcome_var,
        metric_type=metric_type, effect=effect, se=se,
        ci_lo=ci_lo, ci_hi=ci_hi, n=n,
        direction=direction, outcome_type=outcome_type, notes=notes,
    )


ESTIMATES = [
    # ════════════════════════════════════════════════════════════════════════
    # Padmakumar & He (2024) — Does Writing With Language Models Reduce Content Diversity?
    # 15 outcomes. Mostly corpus-level homogenization metrics.
    # ════════════════════════════════════════════════════════════════════════
    _e("padmakumar_he_2024", 1, "Corpus homogenization (Rouge-L, key point)",
       "InstructGPT-assisted essays", "Solo essays",
       "Pairwise Rouge-L on key points", "rouge", 0.1660-0.1536,
       n=200, direction=-1, outcome_type="homogenization",
       notes="p<0.05; InstructGPT 0.1660 vs Solo 0.1536"),
    _e("padmakumar_he_2024", 2, "Corpus homogenization (Rouge-L, GPT3 vs Solo)",
       "GPT3-assisted essays", "Solo essays",
       "Pairwise Rouge-L on key points", "rouge", 0.1578-0.1536,
       n=200, direction=0, outcome_type="homogenization", notes="ns"),
    _e("padmakumar_he_2024", 3, "Corpus homogenization (BertScore, key point)",
       "InstructGPT", "Solo", "BertScore similarity (key point)",
       "bertscore", 0.6437-0.6305, n=200, direction=-1,
       outcome_type="homogenization", notes="p<0.05"),
    _e("padmakumar_he_2024", 4, "Corpus homogenization (Rouge-L, essay-level)",
       "InstructGPT", "Solo", "Essay-level Rouge-L",
       "rouge", 0.1621-0.1498, n=200, direction=-1,
       outcome_type="homogenization", notes="p<0.05"),
    _e("padmakumar_he_2024", 5, "Corpus homogenization (BertScore, essay-level)",
       "InstructGPT", "Solo", "Essay-level BertScore",
       "bertscore", 0.6318-0.6044, n=200, direction=-1,
       outcome_type="homogenization", notes="p<0.05"),
    _e("padmakumar_he_2024", 6, "Lexical diversity (unique 2-grams)",
       "InstructGPT", "Solo", "Fraction unique 2-grams",
       "distinct_n", 0.579-0.602, n=200, direction=-1,
       outcome_type="diversity", notes="permutation p<0.05"),
    _e("padmakumar_he_2024", 7, "Lexical diversity (unique 3-grams)",
       "InstructGPT", "Solo", "Fraction unique 3-grams",
       "distinct_n", 0.869-0.898, n=200, direction=-1,
       outcome_type="diversity"),
    _e("padmakumar_he_2024", 8, "Key-point diversity (Rouge-L 0.6 thr)",
       "InstructGPT", "Solo", "Fraction unique key points (Rouge-L thr 0.6)",
       "other", 0.877-0.941, n=200, direction=-1,
       outcome_type="diversity", notes="permutation p<0.05"),
    _e("padmakumar_he_2024", 9, "Key-point diversity (BertScore 0.2 thr)",
       "InstructGPT", "Solo", "Fraction unique key points (BertScore thr 0.2)",
       "other", 0.941-0.981, n=200, direction=-1, outcome_type="diversity"),
    _e("padmakumar_he_2024", 10, "Compression ratio (LZMA)",
       "InstructGPT", "Solo", "LZMA compression ratio",
       "other", 0.293-0.305, n=200, direction=-1, outcome_type="diversity"),
    _e("padmakumar_he_2024", 11, "Self-diversity of suggestions (Rouge-L)",
       "InstructGPT suggestions", "GPT3 suggestions",
       "Avg pairwise Rouge-L of 5 generations", "rouge", 0.20-0.11,
       direction=-1, outcome_type="diversity",
       notes="RLHF model less diverse; p<0.05"),
    _e("padmakumar_he_2024", 12, "Essay quality — Relevance (1-5)",
       "InstructGPT", "Solo", "Human rating: Relevance", "raw_mean",
       4.10-4.30, n=30, direction=0, outcome_type="individual_creativity",
       notes="ns"),
    _e("padmakumar_he_2024", 13, "Essay quality — Depth (1-5)",
       "InstructGPT", "Solo", "Human rating: Depth of discussion",
       "raw_mean", 3.80-3.95, n=30, direction=0,
       outcome_type="individual_creativity", notes="ns"),
    _e("padmakumar_he_2024", 14, "Perplexity (GPT2)",
       "InstructGPT", "Solo", "GPT2 perplexity",
       "other", 20.26-25.067, n=200, direction=-1,
       outcome_type="diversity", notes="Lower = closer to LM distribution"),
    _e("padmakumar_he_2024", 15, "Sentence length",
       "InstructGPT", "Solo", "Mean words per sentence",
       "raw_mean", 22.51-23.51, se=0.25, n=200, direction=-1,
       outcome_type="other"),

    # ════════════════════════════════════════════════════════════════════════
    # Doshi & Hauser (2024) — Generative AI Enhances Individual Creativity
    # 23 outcomes. OLS coefficients (raw mean differences) on 9-pt Likert.
    # ════════════════════════════════════════════════════════════════════════
    _e("doshi_hauser_2024", 1, "Novelty (1 AI idea)",
       "Human + 1 GenAI idea", "Human-only",
       "Novelty index (9-pt)", "raw_mean", 0.207, n=293,
       direction=1, outcome_type="individual_creativity",
       notes="OLS coef; +5.4%; p=0.021"),
    _e("doshi_hauser_2024", 2, "Novelty (5 AI ideas)",
       "Human + 5 GenAI ideas", "Human-only",
       "Novelty index", "raw_mean", 0.311, n=293,
       direction=1, outcome_type="individual_creativity",
       notes="+8.1%; p<0.001"),
    _e("doshi_hauser_2024", 3, "Usefulness (1 AI idea)",
       "Human + 1 GenAI idea", "Human-only",
       "Usefulness index", "raw_mean", 0.185, n=293,
       direction=1, outcome_type="individual_creativity",
       notes="+3.7%; p=0.039"),
    _e("doshi_hauser_2024", 4, "Usefulness (5 AI ideas)",
       "Human + 5 GenAI ideas", "Human-only",
       "Usefulness index", "raw_mean", 0.453, n=293,
       direction=1, outcome_type="individual_creativity",
       notes="+9.0%; p<0.001"),
    _e("doshi_hauser_2024", 5, "Enjoyability (1 AI idea)",
       "Human + 1 GenAI idea", "Human-only", "How enjoyable",
       "raw_mean", 0.216, n=293, direction=1,
       outcome_type="individual_creativity", notes="p=0.028"),
    _e("doshi_hauser_2024", 6, "Enjoyability (5 AI ideas)",
       "Human + 5 GenAI ideas", "Human-only", "How enjoyable",
       "raw_mean", 0.375, n=293, direction=1,
       outcome_type="individual_creativity", notes="p<0.001"),
    _e("doshi_hauser_2024", 7, "Plot twist (1 AI idea)",
       "Human + 1 GenAI idea", "Human-only", "Has plot twist",
       "raw_mean", 0.384, n=293, direction=1,
       outcome_type="individual_creativity", notes="p<0.001"),
    _e("doshi_hauser_2024", 8, "Plot twist (5 AI ideas)",
       "Human + 5 GenAI ideas", "Human-only", "Has plot twist",
       "raw_mean", 0.468, n=293, direction=1,
       outcome_type="individual_creativity", notes="p<0.001"),
    _e("doshi_hauser_2024", 9, "Well-written (5 AI ideas)",
       "Human + 5 GenAI ideas", "Human-only", "How well written",
       "raw_mean", 0.372, n=293, direction=1,
       outcome_type="individual_creativity", notes="p<0.001"),
    _e("doshi_hauser_2024", 10, "Changed expectations",
       "Human + 5 GenAI ideas", "Human-only",
       "Changed reader expectations", "raw_mean", 0.251, n=293,
       direction=1, outcome_type="individual_creativity", notes="p=0.005"),
    _e("doshi_hauser_2024", 11, "Boring (5 AI ideas, inv.)",
       "Human + 5 GenAI ideas", "Human-only", "How boring",
       "raw_mean", -0.200, n=293, direction=1,
       outcome_type="individual_creativity", notes="Less boring; p=0.049"),
    _e("doshi_hauser_2024", 12, "Story similarity to others (1 AI)",
       "Human + 1 GenAI idea", "Human-only",
       "Cosine similarity within condition (×100)",
       "pairwise_cosine", 0.871, n=293, direction=-1,
       outcome_type="homogenization", notes="+10.7% of HO range; p<0.001"),
    _e("doshi_hauser_2024", 13, "Story similarity to others (5 AI)",
       "Human + 5 GenAI ideas", "Human-only",
       "Cosine similarity within condition (×100)",
       "pairwise_cosine", 0.718, n=293, direction=-1,
       outcome_type="homogenization", notes="+8.9% of HO range; p=0.003"),
    _e("doshi_hauser_2024", 14, "Similarity to GenAI idea (1)",
       "Human + 1 GenAI idea", "Human-only",
       "Cosine similarity to AI idea (×100)",
       "pairwise_cosine", 4.29, n=293, direction=-1,
       outcome_type="homogenization", notes="+5.2%; p<0.001"),
    _e("doshi_hauser_2024", 15, "Similarity to GenAI idea (5)",
       "Human + 5 GenAI ideas", "Human-only",
       "Cosine similarity to AI idea (×100)",
       "pairwise_cosine", 4.11, n=293, direction=-1,
       outcome_type="homogenization", notes="+5.0%; p<0.001"),
    _e("doshi_hauser_2024", 16, "Novelty: Low-DAT writers (1 AI)",
       "Low-DAT + 1 AI idea", "Low-DAT human-only",
       "Novelty index", "raw_mean", None, direction=1,
       outcome_type="individual_creativity",
       notes="+6.3% (heterogeneity by writer creativity)"),
    _e("doshi_hauser_2024", 17, "Novelty: Low-DAT writers (5 AI)",
       "Low-DAT + 5 AI ideas", "Low-DAT human-only",
       "Novelty index", "raw_mean", None, direction=1,
       outcome_type="individual_creativity", notes="+10.7%"),
    _e("doshi_hauser_2024", 18, "Well-written: Low-DAT (5 AI)",
       "Low-DAT + 5 AI ideas", "Low-DAT human-only",
       "Well-written", "raw_mean", None, direction=1,
       outcome_type="individual_creativity", notes="+26.6%"),
    _e("doshi_hauser_2024", 19, "Enjoyment: Low-DAT (5 AI)",
       "Low-DAT + 5 AI ideas", "Low-DAT human-only",
       "Enjoyment", "raw_mean", None, direction=1,
       outcome_type="individual_creativity", notes="+22.6%"),

    # ════════════════════════════════════════════════════════════════════════
    # Anderson, Shah & Kreminski (2024) — Homogenization Effects of LLMs on Human Creative Ideation
    # 10 outcomes; all Cohen's d from within-subject paired t-tests (N=33).
    # ════════════════════════════════════════════════════════════════════════
    _e("anderson_shah_kreminski_2024", 1, "Group-level semantic homogenization",
       "ChatGPT (LLM CST)", "Oblique Strategies (non-AI CST)",
       "Cosine similarity of idea to group avg embedding",
       "cohens_d", 0.47, n=33, direction=-1, outcome_type="homogenization",
       notes="ChatGPT more homogenized; t(32)=2.15, p=0.038"),
    _e("anderson_shah_kreminski_2024", 2, "Individual-level homogenization",
       "ChatGPT", "Oblique Strategies",
       "Cosine sim to participant's own avg",
       "cohens_d", 0.12, n=33, direction=0, outcome_type="homogenization",
       notes="ns; t(32)=0.94, p=0.352"),
    _e("anderson_shah_kreminski_2024", 3, "Sense of responsibility for ideas",
       "ChatGPT", "Oblique Strategies", "% personal responsibility",
       "cohens_d", 0.67, n=33, direction=-1, outcome_type="other",
       notes="−15.5pp; t(32)=3.21, p=0.003"),
    _e("anderson_shah_kreminski_2024", 4, "Fluency (idea count)",
       "ChatGPT", "Oblique Strategies", "Ideas per task",
       "cohens_d", 0.32, n=33, direction=1, outcome_type="idea_quantity",
       notes="+1.07 ideas (~15%); p=0.044"),
    _e("anderson_shah_kreminski_2024", 5, "Flexibility (idea categories)",
       "ChatGPT", "Oblique Strategies", "Distinct idea categories",
       "cohens_d", 0.54, n=33, direction=1, outcome_type="diversity",
       notes="~27% more; p=0.001"),
    _e("anderson_shah_kreminski_2024", 6, "Elaboration (word count)",
       "ChatGPT", "Oblique Strategies", "Stoplisted words per idea",
       "cohens_d", 0.48, n=33, direction=1,
       outcome_type="individual_creativity",
       notes="CI excludes zero"),
    _e("anderson_shah_kreminski_2024", 7, "Originality (unique ideas)",
       "ChatGPT", "Oblique Strategies", "Ideas no other participant generated",
       "cohens_d", 0.26, n=33, direction=-1,
       outcome_type="individual_creativity",
       notes="Directionally fewer unique; p=0.108"),
    _e("anderson_shah_kreminski_2024", 8, "Originality (5% threshold)",
       "ChatGPT", "Oblique Strategies",
       "Categories generated by <5%", "cohens_d", 0.02, n=33,
       direction=0, outcome_type="individual_creativity", notes="ns"),
    _e("anderson_shah_kreminski_2024", 9, "Originality (weighted)",
       "ChatGPT", "Oblique Strategies", "Weighted flexibility score",
       "cohens_d", 0.26, n=33, direction=0,
       outcome_type="individual_creativity", notes="ns"),
    _e("anderson_shah_kreminski_2024", 10, "Creativity Support Index",
       "ChatGPT", "Oblique Strategies", "CSI overall %",
       "cohens_d", 0.24, n=36, direction=0, outcome_type="other",
       notes="ns; self-report"),

    # ════════════════════════════════════════════════════════════════════════
    # Moon et al (2026) — The Creative Link Between Words and Ideas
    # 24 outcomes. Multi-site natural experiment (4 universities) + controlled Exp 3.
    # ════════════════════════════════════════════════════════════════════════
    _e("moon_etal_2026", 1, "Elite Private — word diversity",
       "Post-ChatGPT essays 2024-25", "Pre-ChatGPT 2019-22",
       "Word-level DSI (BERT-large)", "cohens_d", 0.24,
       ci_lo=0.23, ci_hi=0.26, n=71280, direction=1, outcome_type="diversity"),
    _e("moon_etal_2026", 2, "Elite Private — sentence diversity",
       "Post-ChatGPT", "Pre-ChatGPT",
       "Mean pairwise sentence cosine distance (SBERT)",
       "cohens_d", -0.09, ci_lo=-0.10, ci_hi=-0.07, n=71280,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 3, "Elite Private — document distinctness",
       "Post-ChatGPT", "Pre-ChatGPT",
       "Min pairwise document cosine distance",
       "cohens_d", -0.15, ci_lo=-0.17, ci_hi=-0.13, n=71280,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 4, "Regional Private — word diversity",
       "Post-ChatGPT 2024", "Pre-ChatGPT 2020-22",
       "Word-level DSI", "cohens_d", 0.15,
       ci_lo=0.14, ci_hi=0.17, n=66380, direction=1, outcome_type="diversity"),
    _e("moon_etal_2026", 5, "Regional Private — sentence diversity",
       "Post-ChatGPT", "Pre-ChatGPT",
       "Pairwise sentence distance",
       "cohens_d", -0.18, ci_lo=-0.20, ci_hi=-0.16, n=66380,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 6, "Regional Private — document distinctness",
       "Post-ChatGPT", "Pre-ChatGPT", "Min pairwise document distance",
       "cohens_d", -0.08, ci_lo=-0.09, ci_hi=-0.06, n=66380,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 7, "Flagship Public — word diversity",
       "Post-ChatGPT 2024-25", "Pre-ChatGPT 2020-22",
       "Word-level DSI", "cohens_d", 0.15,
       ci_lo=0.14, ci_hi=0.16, n=154650, direction=1, outcome_type="diversity"),
    _e("moon_etal_2026", 8, "Flagship Public — sentence diversity",
       "Post-ChatGPT", "Pre-ChatGPT", "Pairwise sentence distance",
       "cohens_d", -0.15, ci_lo=-0.16, ci_hi=-0.14, n=154650,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 9, "Flagship Public — document distinctness",
       "Post-ChatGPT", "Pre-ChatGPT", "Min pairwise doc distance",
       "cohens_d", -0.09, ci_lo=-0.10, ci_hi=-0.08, n=154650,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 10, "Selective Liberal Arts — word diversity",
       "Post-ChatGPT 2024-25", "Pre-ChatGPT 2018-21",
       "Word-level DSI", "cohens_d", 0.39,
       ci_lo=0.36, ci_hi=0.42, n=21078, direction=1, outcome_type="diversity"),
    _e("moon_etal_2026", 11, "Selective LA — sentence diversity",
       "Post-ChatGPT", "Pre-ChatGPT", "Pairwise sentence distance",
       "cohens_d", -0.06, ci_lo=-0.09, ci_hi=-0.03, n=21078,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 12, "Selective LA — document distinctness",
       "Post-ChatGPT", "Pre-ChatGPT", "Min pairwise doc distance",
       "cohens_d", -0.07, ci_lo=-0.10, ci_hi=-0.04, n=21078,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 13, "Controlled Exp 3 — word (AI-revised)",
       "AI-revised essay (GPT-4.1)", "Original human essay",
       "Word-level DSI (standardized)",
       "raw_mean", 0.79, ci_lo=0.64, ci_hi=0.94, n=203,
       direction=1, outcome_type="diversity", notes="Within-subject"),
    _e("moon_etal_2026", 14, "Controlled Exp 3 — word (AI-generated)",
       "AI-generated essay", "Original human essay",
       "Word-level DSI", "raw_mean", 0.65,
       ci_lo=0.50, ci_hi=0.79, n=203, direction=1,
       outcome_type="diversity"),
    _e("moon_etal_2026", 15, "Controlled Exp 3 — sentence (AI-revised)",
       "AI-revised", "Original", "Sentence diversity (standardized)",
       "raw_mean", -0.47, ci_lo=-0.62, ci_hi=-0.31, n=203,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 16, "Controlled Exp 3 — sentence (AI-generated)",
       "AI-generated", "Original", "Sentence diversity",
       "raw_mean", -0.50, ci_lo=-0.66, ci_hi=-0.35, n=203,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 17, "Controlled Exp 3 — document (AI-revised)",
       "AI-revised", "Original", "Document distinctness (standardized)",
       "raw_mean", -0.98, ci_lo=-1.10, ci_hi=-0.85, n=203,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 18, "Controlled Exp 3 — document (AI-generated)",
       "AI-generated", "Original", "Document distinctness",
       "raw_mean", -1.52, ci_lo=-1.64, ci_hi=-1.40, n=203,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 19, "Word-doc decoupling (Exp 1)",
       "GPT-generated essays", "Human essays",
       "Correlation word-diversity × doc-distinctness",
       "other", -0.283-0.117, n=3000, direction=-1,
       outcome_type="other", notes="GPT r=-0.28 vs Human r=+0.12"),
    _e("moon_etal_2026", 20, "Creativity rating (Elite Private)",
       "Post-ChatGPT", "Pre-ChatGPT",
       "Expert-tuned GPT-4.1-mini rating (standardized)",
       "raw_mean", 0.19, n=312388, direction=1,
       outcome_type="individual_creativity",
       notes="Range 0.19-0.30 across 4 unis; all p<0.001"),
    _e("moon_etal_2026", 21, "Pilot — word diversity",
       "Post-ChatGPT 2024-25", "Pre-ChatGPT 2019-22",
       "Word-level DSI", "cohens_d", 0.26,
       ci_lo=0.16, ci_hi=0.36, n=1800, direction=1,
       outcome_type="diversity"),
    _e("moon_etal_2026", 22, "Pilot — sentence diversity",
       "Post-ChatGPT", "Pre-ChatGPT", "Sentence diversity",
       "cohens_d", -0.13, ci_lo=-0.23, ci_hi=-0.03, n=1800,
       direction=-1, outcome_type="homogenization"),
    _e("moon_etal_2026", 23, "Pilot — document distinctness",
       "Post-ChatGPT", "Pre-ChatGPT", "Document distinctness",
       "cohens_d", -0.24, ci_lo=-0.35, ci_hi=-0.14, n=1800,
       direction=-1, outcome_type="homogenization"),

    # ════════════════════════════════════════════════════════════════════════
    # Ashkinaze et al (2025) — How AI Ideas Affect Creativity, Diversity, Evolution
    # 12 outcomes. Cliff's delta + regression betas.
    # ════════════════════════════════════════════════════════════════════════
    _e("ashkinaze_etal_2025", 1, "Global diversity (High AI, disclosed)",
       "High AI exposure (4 AI/2 human), disclosed", "Control (0 AI/6 human)",
       "Median pairwise cosine distance",
       "other", 0.31, n=683, direction=1,
       outcome_type="diversity", notes="Cliff's δ; p=0.001"),
    _e("ashkinaze_etal_2025", 2, "Global diversity (High AI, undisclosed)",
       "High AI, undisclosed", "Control",
       "Median pairwise cosine distance",
       "other", 0.26, n=683, direction=1,
       outcome_type="diversity", notes="Cliff's δ; p=0.001"),
    _e("ashkinaze_etal_2025", 3, "Global diversity (Low AI, undisclosed)",
       "Low AI (2 AI/4 human), undisclosed", "Control",
       "Median pairwise cosine distance",
       "other", 0.11, n=683, direction=1,
       outcome_type="diversity", notes="Cliff's δ; p=0.001"),
    _e("ashkinaze_etal_2025", 4, "Global diversity (Low AI, disclosed)",
       "Low AI, disclosed", "Control",
       "Median pairwise cosine distance",
       "other", None, n=683, direction=0, outcome_type="diversity",
       notes="ns after Holm-Bonferroni"),
    _e("ashkinaze_etal_2025", 5, "Diversity evolution (Control slope)",
       "Trial number (1-20)", "—",
       "Within-condition trial slope on diversity",
       "raw_mean", -0.39, ci_lo=-0.73, ci_hi=-0.05, n=350,
       direction=-1, outcome_type="diversity",
       notes="Diversity declines over rounds in Control"),
    _e("ashkinaze_etal_2025", 6, "Diversity evolution (High undisclosed × trial)",
       "High AI, undisclosed × trial", "Control",
       "Interaction coef on diversity slope",
       "raw_mean", 0.53, ci_lo=0.06, ci_hi=0.99, n=350,
       direction=1, outcome_type="diversity"),
    _e("ashkinaze_etal_2025", 7, "Diversity evolution (High disclosed × trial)",
       "High AI, disclosed × trial", "Control",
       "Interaction coef on diversity slope",
       "raw_mean", 0.57, ci_lo=0.10, ci_hi=1.03, n=350,
       direction=1, outcome_type="diversity"),
    _e("ashkinaze_etal_2025", 8, "Individual creativity (main effect)",
       "All AI-exposure conditions", "Control",
       "Originality (Organisciak GPT-3 classifier)",
       "other", 0, n=3414, direction=0,
       outcome_type="individual_creativity",
       notes="F(4,19.86)=0.12, p=0.97; null"),
    _e("ashkinaze_etal_2025", 9, "AI adoption: low-creativity ppts (disclosure effect)",
       "Bottom 10% self-perceived creativity, disclosed vs undisclosed contrast",
       "Same contrast in high-creativity ppts",
       "Max cosine similarity to AI examples",
       "cohens_d", 0.65, n=2588, direction=-1,
       outcome_type="homogenization",
       notes="Low-creativity adopt AI more when undisclosed; p=0.03"),

    # ════════════════════════════════════════════════════════════════════════
    # Meincke, Mollick & Terwiesch (2024) — Prompting Diverse Ideas
    # 11 outcomes. All pairwise cosine similarities (lower = more diverse).
    # ════════════════════════════════════════════════════════════════════════
    _e("meincke_mollick_terwiesch_2024", 1, "GPT-4 base vs Humans",
       "GPT-4 base prompt", "Wharton MBA students",
       "Mean within-pool cosine similarity",
       "pairwise_cosine", 0.377-0.243, direction=-1,
       outcome_type="homogenization", notes="GPT-4 0.377 vs Human 0.243; p<0.01"),
    _e("meincke_mollick_terwiesch_2024", 2, "GPT-4 CoT vs Humans",
       "GPT-4 Chain-of-Thought", "Wharton MBA students",
       "Mean within-pool cosine similarity",
       "pairwise_cosine", 0.255-0.243, direction=-1,
       outcome_type="homogenization", notes="CoT 0.255 nearly matches Human 0.243"),
    _e("meincke_mollick_terwiesch_2024", 3, "GPT-4 CoT vs Base",
       "GPT-4 Chain-of-Thought", "GPT-4 base",
       "Mean within-pool cosine similarity",
       "pairwise_cosine", 0.255-0.377, direction=1,
       outcome_type="diversity",
       notes="CoT reduces similarity (more diverse); p<0.01"),
    _e("meincke_mollick_terwiesch_2024", 4, "Steve Jobs persona vs Base",
       "Steve Jobs persona prompt", "GPT-4 base",
       "Cosine similarity",
       "pairwise_cosine", 0.368-0.377, direction=1,
       outcome_type="diversity"),
    _e("meincke_mollick_terwiesch_2024", 5, "Creative Entrepreneur vs Base",
       "Creative Entrepreneur persona", "GPT-4 base",
       "Cosine similarity",
       "pairwise_cosine", 0.348-0.377, direction=1,
       outcome_type="diversity"),
    _e("meincke_mollick_terwiesch_2024", 6, "Cosine info vs Base",
       "GPT-4 informed of own cosine sim", "GPT-4 base",
       "Cosine similarity",
       "pairwise_cosine", 0.432-0.377, direction=-1,
       outcome_type="homogenization", notes="Made it worse"),
    _e("meincke_mollick_terwiesch_2024", 7, "Girotra baseline GPT-4 vs Humans",
       "Girotra GPT-4 baseline", "Wharton MBA students",
       "Cosine similarity",
       "pairwise_cosine", 0.415-0.243, direction=-1,
       outcome_type="homogenization"),
    _e("meincke_mollick_terwiesch_2024", 8, "Unique-ideas pool size (CoT)",
       "GPT-4 CoT", "GPT-4 base",
       "Opportunity-space size (Kornish-Ulrich)",
       "other", 4700-3700, direction=1,
       outcome_type="idea_quantity", notes="4700 vs 3700 estimated unique ideas"),
    _e("meincke_mollick_terwiesch_2024", 9, "Repetition rate (CoT)",
       "GPT-4 CoT", "GPT-4 base",
       "Share repetitive ideas (cosine ≥0.8)",
       "other", 0.117-0.138, direction=1, outcome_type="diversity"),

    # ════════════════════════════════════════════════════════════════════════
    # Si, Yang & Hashimoto (2025) — Can LLMs Generate Novel Research Ideas?
    # 13 outcomes. Means + SDs reported, so Cohen's d computable.
    # ════════════════════════════════════════════════════════════════════════
    _e("si_yang_hashimoto_2025", 1, "Novelty (Test 1)",
       "AI research ideas (Claude-3.5)", "Human expert ideas",
       "Novelty (1-10)", "cohens_d", 0.45, n=228, direction=1,
       outcome_type="individual_creativity",
       notes="AI 5.64±1.76 vs Human 4.84±1.79; p<0.01"),
    _e("si_yang_hashimoto_2025", 2, "Novelty (AI+Human Rerank)",
       "AI ideas + human rerank", "Human expert ideas",
       "Novelty (1-10)", "cohens_d", 0.56, n=228, direction=1,
       outcome_type="individual_creativity",
       notes="5.81±1.66 vs 4.84±1.79; p<0.001"),
    _e("si_yang_hashimoto_2025", 3, "Excitement (Test 1)",
       "AI ideas", "Human expert ideas", "Excitement (1-10)",
       "cohens_d", 0.35, n=228, direction=1,
       outcome_type="individual_creativity",
       notes="5.19±1.73 vs 4.55±1.89; p=0.04"),
    _e("si_yang_hashimoto_2025", 4, "Excitement (AI+Rerank)",
       "AI + Rerank", "Human", "Excitement",
       "cohens_d", 0.49, n=228, direction=1,
       outcome_type="individual_creativity", notes="p<0.01"),
    _e("si_yang_hashimoto_2025", 5, "Feasibility",
       "AI ideas", "Human ideas", "Feasibility (1-10)",
       "cohens_d", -0.14, n=228, direction=-1,
       outcome_type="individual_creativity",
       notes="6.34±1.88 vs 6.61±1.99; ns"),
    _e("si_yang_hashimoto_2025", 6, "Feasibility (AI+Rerank)",
       "AI+Rerank", "Human", "Feasibility",
       "cohens_d", -0.09, n=228, direction=0,
       outcome_type="individual_creativity", notes="ns"),
    _e("si_yang_hashimoto_2025", 7, "Expected Effectiveness",
       "AI ideas", "Human", "Expected Effectiveness (1-10)",
       "cohens_d", 0.20, n=228, direction=0,
       outcome_type="individual_creativity", notes="ns; p=0.67"),
    _e("si_yang_hashimoto_2025", 8, "Expected Effectiveness (AI+Rerank)",
       "AI+Rerank", "Human", "Expected Effectiveness",
       "cohens_d", 0.26, n=228, direction=0,
       outcome_type="individual_creativity", notes="ns"),
    _e("si_yang_hashimoto_2025", 9, "Overall Score",
       "AI ideas", "Human", "Overall Score (1-10)",
       "cohens_d", 0.09, n=228, direction=0,
       outcome_type="individual_creativity", notes="ns"),
    _e("si_yang_hashimoto_2025", 10, "Overall Score (AI+Rerank)",
       "AI+Rerank", "Human", "Overall Score",
       "cohens_d", 0.36, n=228, direction=1,
       outcome_type="individual_creativity", notes="p=0.04"),
    _e("si_yang_hashimoto_2025", 11, "Novelty (Test 2, per-idea)",
       "AI ideas", "Human ideas", "Novelty (per-idea avg)",
       "cohens_d", 0.57, n=98, direction=1,
       outcome_type="individual_creativity",
       notes="5.62±1.39 vs 4.86±1.26; p=0.03"),
    _e("si_yang_hashimoto_2025", 12, "Novelty (Test 3, paired)",
       "AI ideas", "Human ideas",
       "Within-reviewer paired novelty diff",
       "raw_mean", 0.94, n=70, direction=1,
       outcome_type="individual_creativity", notes="p<0.001"),
    _e("si_yang_hashimoto_2025", 13, "LLM idea diversity (scaling)",
       "Claude-3.5 generating 4000 ideas", "—",
       "Non-duplicate ideas (cosine threshold 0.8)",
       "pairwise_cosine", None, direction=-1,
       outcome_type="homogenization",
       notes="Only ~200 unique out of 4000 generated; plateau"),

    # ════════════════════════════════════════════════════════════════════════
    # Liu et al (2024) — When ChatGPT is Gone: Creativity Reverts, Homogeneity Persists
    # 20 outcomes. Persistence study (Day 1, 2-6 with AI, Day 7/30 no AI).
    # ════════════════════════════════════════════════════════════════════════
    _e("liu_etal_2024", 1, "AUT Novelty (Day 1 baseline)",
       "ChatGPT group, pre-AI", "No-AI group",
       "Novelty (AUT)", "raw_mean", 8.78-7.50, n=61, direction=0,
       outcome_type="individual_creativity", notes="Baseline; ns"),
    _e("liu_etal_2024", 2, "AUT Novelty (Day 6 with AI, peak)",
       "ChatGPT group with AI", "No-AI group",
       "Novelty (AUT)", "raw_mean", 25.04, n=61, direction=1,
       outcome_type="individual_creativity",
       notes="t=-4.84, p<0.001; d≈1.25 (from t)"),
    _e("liu_etal_2024", 3, "AUT Novelty (Day 7 — AI REMOVED)",
       "Previously AI", "Never AI", "Novelty (AUT)",
       "raw_mean", 4.58, n=61, direction=0,
       outcome_type="individual_creativity",
       notes="Persistence: reverts to baseline; t=-1.98, p=0.053"),
    _e("liu_etal_2024", 4, "AUT Novelty (Day 30 follow-up)",
       "Previously AI", "Never AI", "Novelty (AUT)",
       "raw_mean", 3.69, n=61, direction=1,
       outcome_type="individual_creativity",
       notes="Small persistence; p=0.038"),
    _e("liu_etal_2024", 5, "AUT Usefulness (Day 7)",
       "Previously AI", "Never AI", "Usefulness (AUT)",
       "raw_mean", -0.54, n=61, direction=0,
       outcome_type="individual_creativity", notes="ns"),
    _e("liu_etal_2024", 6, "Problem-solving creativity (Day 6 peak)",
       "ChatGPT with AI", "No-AI", "Creativity Task 2",
       "raw_mean", 1.00, n=61, direction=1,
       outcome_type="individual_creativity",
       notes="Control 2.53 vs GPT 3.53; t=-4.39, p<0.001"),
    _e("liu_etal_2024", 7, "Problem-solving creativity (Day 7 — REMOVED)",
       "Previously AI", "Never AI", "Creativity Task 2",
       "raw_mean", 0.52, n=61, direction=0,
       outcome_type="individual_creativity", notes="Reverts; ns"),
    _e("liu_etal_2024", 8, "SBERT homogeneity (Days 2-6 with AI)",
       "ChatGPT with AI", "No-AI",
       "Pairwise cosine similarity (AUT)",
       "pairwise_cosine", 0.50-0.40, n=61, direction=-1,
       outcome_type="homogenization",
       notes="Day-by-day all p<0.01"),
    _e("liu_etal_2024", 9, "SBERT homogeneity (Day 7 — REMOVED)",
       "Previously AI", "Never AI", "Pairwise cosine (AUT)",
       "pairwise_cosine", 0.36-0.33, n=61, direction=-1,
       outcome_type="homogenization", notes="Persistence borderline"),
    _e("liu_etal_2024", 10, "SBERT homogeneity (Day 30 — REMOVED)",
       "Previously AI", "Never AI", "Pairwise cosine (AUT)",
       "pairwise_cosine", 0.39-0.33, n=61, direction=-1,
       outcome_type="homogenization", notes="Persists; p≤0.001"),
    _e("liu_etal_2024", 11, "String redundancy (Days 2-6)",
       "ChatGPT with AI", "No-AI",
       "Count of repeated strings ≥2 chars",
       "other", 7.0-3.3, n=61, direction=-1,
       outcome_type="homogenization", notes="Range 5.9-8.7 vs 3.1-3.4; p≤0.01"),
    _e("liu_etal_2024", 12, "String redundancy (Day 7 — REMOVED)",
       "Previously AI", "Never AI", "String redundancy",
       "other", 3.74-2.76, n=61, direction=-1,
       outcome_type="homogenization", notes="Persists"),
    _e("liu_etal_2024", 13, "String redundancy (Day 30 — REMOVED)",
       "Previously AI", "Never AI", "String redundancy",
       "other", 2.34-1.45, n=61, direction=-1,
       outcome_type="homogenization", notes="Persists; p≤0.001"),
    _e("liu_etal_2024", 14, "Task 2 SBERT homogeneity (Days 2-6)",
       "ChatGPT with AI", "No-AI",
       "Pairwise cosine (problem-solving)",
       "pairwise_cosine", 0.70-0.57, n=61, direction=-1,
       outcome_type="homogenization", notes="all p≤0.001"),
    _e("liu_etal_2024", 15, "Task 2 String redundancy (Days 2-6)",
       "ChatGPT with AI", "No-AI",
       "Repeated-string count (problem-solving)",
       "other", 205.0-58.0, n=61, direction=-1,
       outcome_type="homogenization", notes="Very large effect; p≤0.001"),
    _e("liu_etal_2024", 16, "Task 2 String redundancy (Day 7 — REMOVED)",
       "Previously AI", "Never AI", "String redundancy (Task 2)",
       "other", 75.28-54.74, n=61, direction=-1,
       outcome_type="homogenization", notes="Persists; p≤0.001"),
    _e("liu_etal_2024", 17, "Semantic density (Day 7+30)",
       "Previously AI", "Never AI",
       "UMAP-density SD / eigenvalues / ellipse area",
       "other", None, n=61, direction=-1,
       outcome_type="homogenization",
       notes="GPT group consistently smaller; persists no p-values"),

    # ════════════════════════════════════════════════════════════════════════
    # Moon, Green & Kushlev (2025) — Homogenizing Effect of LLMs on Creative Diversity
    # 16 outcomes. Cohen's d for individual diversity; log-linear slopes for DGR.
    # ════════════════════════════════════════════════════════════════════════
    _e("moon_green_kushlev_2025", 1, "Individual DSI (Study 1, Base GPT-4)",
       "Base GPT-4 essays", "Human essays",
       "Divergent Semantic Integration", "cohens_d", -1.38,
       ci_lo=-10.76, ci_hi=-7.14, n=200, direction=-1,
       outcome_type="individual_creativity",
       notes="Cohen's d=1.38 favoring human; t(159.89)=9.75"),
    _e("moon_green_kushlev_2025", 2, "Diversity Growth Rate (S1)",
       "Base GPT-4", "Human", "DGR log-linear slope",
       "other", -0.40, ci_lo=-0.50, ci_hi=-0.29, n=200,
       direction=-1, outcome_type="homogenization",
       notes="Human b=0.58 vs GPT b=0.18; p<0.001"),
    _e("moon_green_kushlev_2025", 3, "Individual DSI (S2, Base GPT-4)",
       "Base GPT-4", "Human", "DSI", "cohens_d", -0.74,
       ci_lo=-6.34, ci_hi=-2.87, n=400, direction=-1,
       outcome_type="individual_creativity", notes="p_holm<0.001"),
    _e("moon_green_kushlev_2025", 4, "Individual DSI (S2, Naive-prompted)",
       "Naive-prompted GPT-4", "Human", "DSI",
       "cohens_d", 0.00, ci_lo=-1.76, ci_hi=1.72, n=400,
       direction=0, outcome_type="individual_creativity",
       notes="No difference; p_holm=0.982"),
    _e("moon_green_kushlev_2025", 5, "Individual DSI (S2, Parameter-modified)",
       "Parameter-modified GPT-4 (presence/freq penalty=2)", "Human",
       "DSI", "cohens_d", 2.66, ci_lo=14.88, ci_hi=18.35, n=400,
       direction=1, outcome_type="individual_creativity",
       notes="AI > human; t(396)=-18.81, p_holm<0.001"),
    _e("moon_green_kushlev_2025", 6, "DGR (S2, Base GPT-4)",
       "Base GPT-4", "Human", "DGR slope",
       "other", -0.43, ci_lo=-0.58, ci_hi=-0.28, n=400,
       direction=-1, outcome_type="homogenization"),
    _e("moon_green_kushlev_2025", 7, "DGR (S2, Naive-prompted)",
       "Naive-prompted GPT-4", "Human", "DGR slope",
       "other", -0.39, ci_lo=-0.54, ci_hi=-0.24, n=400,
       direction=-1, outcome_type="homogenization"),
    _e("moon_green_kushlev_2025", 8, "DGR (S2, Parameter-modified)",
       "Parameter-modified GPT-4", "Human", "DGR slope",
       "other", -0.25, ci_lo=-0.40, ci_hi=-0.10, n=400,
       direction=-1, outcome_type="homogenization",
       notes="Higher individual diversity but still homogenizes collectively"),
    _e("moon_green_kushlev_2025", 9, "Individual DSI (S3, Base GPT-4)",
       "Base GPT-4 (n=400)", "Random human (n=400)",
       "DSI", "cohens_d", -2.09, ci_lo=-14.03, ci_hi=-12.13, n=1600,
       direction=-1, outcome_type="individual_creativity",
       notes="Largest individual effect; t(1596)=26.94"),
    _e("moon_green_kushlev_2025", 10, "Individual DSI (S3, CoT-prompted)",
       "CoT-prompted GPT-4", "Human", "DSI",
       "cohens_d", -1.56, ci_lo=-11.65, ci_hi=-9.75, n=800,
       direction=-1, outcome_type="individual_creativity"),
    _e("moon_green_kushlev_2025", 11, "CoT vs Base GPT-4 (S3)",
       "CoT-prompted GPT-4", "Base GPT-4", "DSI",
       "cohens_d", 0.35, n=800, direction=1,
       outcome_type="individual_creativity",
       notes="CoT improves over base AI (within-AI)"),
    _e("moon_green_kushlev_2025", 12, "Base GPT-4 vs Diverse Human (S3)",
       "Base GPT-4", "Racially/ethnically diverse human", "DSI",
       "cohens_d", -1.87, ci_lo=-13.78, ci_hi=-11.88, n=800,
       direction=-1, outcome_type="individual_creativity"),
    _e("moon_green_kushlev_2025", 13, "CoT vs Diverse Human (S3)",
       "CoT-prompted GPT-4", "Diverse human", "DSI",
       "cohens_d", -1.52, ci_lo=-11.41, ci_hi=-9.50, n=800,
       direction=-1, outcome_type="individual_creativity"),
    _e("moon_green_kushlev_2025", 14, "DGR (S3, Base GPT-4)",
       "Base GPT-4", "Random human", "DGR slope",
       "other", -0.54, ci_lo=-0.69, ci_hi=-0.39, n=1600,
       direction=-1, outcome_type="homogenization",
       notes="Strongest DGR gap; GPT-4 ~11% of human"),
    _e("moon_green_kushlev_2025", 15, "DGR (S3, CoT-prompted)",
       "CoT-prompted GPT-4", "Random human", "DGR slope",
       "other", -0.31, ci_lo=-0.46, ci_hi=-0.16, n=1600,
       direction=-1, outcome_type="homogenization",
       notes="Human ~2x CoT"),

    # ════════════════════════════════════════════════════════════════════════
    # Meincke, Nave & Terwiesch (2025) — ChatGPT Decreases Idea Diversity in Brainstorming
    # 12 outcomes. Fraction-unique-ideas (cosine threshold 0.8).
    # ════════════════════════════════════════════════════════════════════════
    _e("meincke_nave_terwiesch_2025", 1, "Unique fraction (Exp 1)",
       "ChatGPT-assisted brainstorming", "Web-search-assisted",
       "% unique idea concepts (cosine threshold 0.8)",
       "other", 0.74-0.96, direction=-1, outcome_type="diversity",
       notes="ChatGPT 0.74 vs Web 0.96"),
    _e("meincke_nave_terwiesch_2025", 2, "Unique fraction (Exp 2A, vs Web)",
       "ChatGPT", "Web search",
       "% unique ideas", "other", 0.70-0.92, direction=-1,
       outcome_type="diversity"),
    _e("meincke_nave_terwiesch_2025", 3, "Unique fraction (Exp 2A, vs Human)",
       "ChatGPT", "Human (unaided)",
       "% unique ideas", "other", 0.70-0.91, direction=-1,
       outcome_type="diversity"),
    _e("meincke_nave_terwiesch_2025", 4, "Unique fraction (Exp 2B, ChatGPT-only)",
       "ChatGPT-only", "Human-only",
       "% unique ideas", "other", 0.06-1.00, direction=-1,
       outcome_type="diversity", notes="Most dramatic: 6% vs 100%"),
    _e("meincke_nave_terwiesch_2025", 5, "Unique fraction (Exp 2B, ChatGPT+Human)",
       "ChatGPT-human collaborative", "Human-only",
       "% unique ideas", "other", 0.41-1.00, direction=-1,
       outcome_type="diversity"),
    _e("meincke_nave_terwiesch_2025", 6, "Unique fraction (Exp 3)",
       "ChatGPT", "Web search", "% unique ideas",
       "other", 0.88-1.00, direction=-1, outcome_type="diversity"),
    _e("meincke_nave_terwiesch_2025", 7, "Unique fraction (Exp 4, low constraints)",
       "ChatGPT low-constraints", "Web search low-constraints",
       "% unique ideas", "other", 0.94-1.00, direction=-1,
       outcome_type="diversity", notes="ns; ceiling"),
    _e("meincke_nave_terwiesch_2025", 8, "Unique fraction (Exp 4, high constraints)",
       "ChatGPT high-constraints", "Web search high-constraints",
       "% unique ideas", "other", 0.93-0.99, direction=-1,
       outcome_type="diversity", notes="ns; ceiling"),
    _e("meincke_nave_terwiesch_2025", 9, "Unique fraction (Exp 5, base empathy)",
       "ChatGPT empathy base", "Web search empathy base",
       "% unique ideas", "other", 0.59-0.98, direction=-1,
       outcome_type="diversity"),
    _e("meincke_nave_terwiesch_2025", 10, "Unique fraction (Exp 5, high empathy)",
       "ChatGPT empathy high", "Web search empathy high",
       "% unique ideas", "other", 0.63-0.98, direction=-1,
       outcome_type="diversity"),
    _e("meincke_nave_terwiesch_2025", 11, "Sprinkler-word concentration (Exp 2A)",
       "ChatGPT", "Web search / Human",
       "Count ideas with 'sprinkler' (of 96)",
       "raw_mean", 20-7, n=96, direction=-1,
       outcome_type="homogenization",
       notes="ChatGPT 20 vs Web 7 vs Human 12"),
    _e("meincke_nave_terwiesch_2025", 12, "Identical-name ideas (Exp 2B)",
       "ChatGPT-only", "Human-only",
       "Identical-name 'Build-a-Breeze Castle' count",
       "raw_mean", 9, direction=-1, outcome_type="homogenization",
       notes="9 identical vs 0 human"),

    # ════════════════════════════════════════════════════════════════════════
    # Lee & Chung (2024) — Empirical Investigation of ChatGPT on Creativity
    # 17 outcomes. Cohen's d throughout; 5 experiments.
    # ════════════════════════════════════════════════════════════════════════
    _e("lee_chung_2024", 1, "Creativity (Exp 1, lay judges)",
       "ChatGPT-assisted", "Web-search-assisted",
       "Creativity (6-item, originality + appropriateness)",
       "cohens_d", 0.49, ci_lo=0.22, ci_hi=0.75, n=233,
       direction=1, outcome_type="individual_creativity",
       notes="ChatGPT 4.28±0.81 vs Web 3.89±0.80; p=2.87e-4"),
    _e("lee_chung_2024", 2, "Creativity (Exp 1, expert judges)",
       "ChatGPT", "Web search", "Creativity (expert)",
       "cohens_d", 0.34, ci_lo=0.08, ci_hi=0.61, n=233,
       direction=1, outcome_type="individual_creativity",
       notes="3.06±1.40 vs 2.65±0.98; p=0.010"),
    _e("lee_chung_2024", 3, "Creativity (Exp 2A, vs Web)",
       "ChatGPT", "Web search", "Creativity (lay)",
       "cohens_d", 0.71, ci_lo=0.42, ci_hi=1.00, n=291,
       direction=1, outcome_type="individual_creativity",
       notes="4.56±0.75 vs 3.98±0.94; p=1.16e-6"),
    _e("lee_chung_2024", 4, "Creativity (Exp 2A, vs Human-only)",
       "ChatGPT", "Human-only", "Creativity (lay)",
       "cohens_d", 0.56, ci_lo=0.27, ci_hi=0.85, n=291,
       direction=1, outcome_type="individual_creativity",
       notes="4.56 vs 4.11; p=1.45e-4"),
    _e("lee_chung_2024", 5, "Creativity (Exp 2B, ChatGPT-assisted vs Human)",
       "ChatGPT-assisted", "Human-only", "Creativity (lay)",
       "cohens_d", 1.88, ci_lo=1.56, ci_hi=2.20, n=300,
       direction=1, outcome_type="individual_creativity",
       notes="Largest effect; 4.84 vs 3.66"),
    _e("lee_chung_2024", 6, "Creativity (Exp 2B, ChatGPT-only vs Human)",
       "ChatGPT-only (raw GPT-3.5)", "Human-only",
       "Creativity (lay)", "cohens_d", 1.88,
       ci_lo=1.56, ci_hi=2.20, n=300, direction=1,
       outcome_type="individual_creativity",
       notes="Raw AI alone matches human-AI"),
    _e("lee_chung_2024", 7, "Creativity (Exp 2B, Assisted vs Only)",
       "ChatGPT-assisted", "ChatGPT-only", "Creativity (lay)",
       "cohens_d", 0.00, ci_lo=-0.27, ci_hi=0.28, n=300,
       direction=0, outcome_type="individual_creativity",
       notes="No human-edit value-add; BF=0.15"),
    _e("lee_chung_2024", 8, "Creativity (Exp 3, dining table)",
       "ChatGPT", "Web search", "Creativity (lay)",
       "cohens_d", 0.37, ci_lo=0.09, ci_hi=0.66, n=194,
       direction=1, outcome_type="individual_creativity",
       notes="4.60 vs 4.35; p=0.010"),
    _e("lee_chung_2024", 9, "Creativity (Exp 4, high constraints)",
       "ChatGPT × High constraints", "Web × High constraints",
       "Creativity (lay)", "cohens_d", 0.32,
       ci_lo=0.04, ci_hi=0.60, n=400, direction=1,
       outcome_type="individual_creativity", notes="p=0.025"),
    _e("lee_chung_2024", 10, "Creativity (Exp 4, low constraints)",
       "ChatGPT × Low constraints", "Web × Low constraints",
       "Creativity (lay)", "cohens_d", 0.34,
       ci_lo=0.06, ci_hi=0.63, n=400, direction=1,
       outcome_type="individual_creativity", notes="p=0.017"),
    _e("lee_chung_2024", 11, "Creativity (Exp 5, high empathy)",
       "ChatGPT × High empathy", "Web × High empathy",
       "Creativity (lay)", "cohens_d", 0.77,
       ci_lo=0.48, ci_hi=1.07, n=383, direction=1,
       outcome_type="individual_creativity", notes="p=2.44e-7"),
    _e("lee_chung_2024", 12, "Creativity (Exp 5, baseline empathy)",
       "ChatGPT × Baseline empathy", "Web × Baseline empathy",
       "Creativity (lay)", "cohens_d", 1.01,
       ci_lo=0.72, ci_hi=1.30, n=383, direction=1,
       outcome_type="individual_creativity", notes="p=1.04e-11"),
    _e("lee_chung_2024", 13, "Originality sub-score (Exp 1)",
       "ChatGPT", "Web search", "Originality sub-score",
       "cohens_d", 0.45, ci_lo=0.18, ci_hi=0.71, n=233,
       direction=1, outcome_type="individual_creativity"),
    _e("lee_chung_2024", 14, "Appropriateness sub-score (Exp 1)",
       "ChatGPT", "Web search", "Appropriateness sub-score",
       "cohens_d", 0.46, ci_lo=0.20, ci_hi=0.72, n=233,
       direction=1, outcome_type="individual_creativity"),
    _e("lee_chung_2024", 15, "Idea quantity (Exp 1)",
       "ChatGPT", "Web search", "Ideas per participant",
       "cohens_d", 0.19, n=233, direction=0,
       outcome_type="idea_quantity", notes="ns; p=0.149"),
    _e("lee_chung_2024", 16, "Creativity (Exp 2B expert, Assisted vs Human)",
       "ChatGPT-assisted", "Human-only",
       "Creativity (expert)", "cohens_d", 1.77,
       ci_lo=1.46, ci_hi=2.09, n=300, direction=1,
       outcome_type="individual_creativity",
       notes="3.85 vs 2.67; replicates lay result"),
    _e("lee_chung_2024", 17, "Creativity (Exp 2B expert, Only vs Human)",
       "ChatGPT-only", "Human-only",
       "Creativity (expert)", "cohens_d", 1.81,
       ci_lo=1.49, ci_hi=2.12, n=300, direction=1,
       outcome_type="individual_creativity"),

    # ════════════════════════════════════════════════════════════════════════
    # Boussioux et al (2024) — The Crowdless Future
    # 16 outcomes. Cohen's d computable from reported means + SDs.
    # ════════════════════════════════════════════════════════════════════════
    _e("boussioux_etal_2024", 1, "Novelty (HAI vs HC mean)",
       "Human-AI combined", "Human Crowd only",
       "Novelty (1-5 Likert)", "cohens_d", -0.146,
       se=0.035, n=3900, direction=-1,
       outcome_type="individual_creativity",
       notes="HC 3.51 vs HAI 3.35; p<0.001"),
    _e("boussioux_etal_2024", 2, "Strategic Viability (HAI vs HC)",
       "Human-AI", "Human Crowd",
       "Strategic Viability (1-5)", "cohens_d", 0.078,
       se=0.037, n=3900, direction=1,
       outcome_type="individual_creativity", notes="p=0.016"),
    _e("boussioux_etal_2024", 3, "Environmental Value (HAI vs HC)",
       "Human-AI", "Human Crowd",
       "Environmental Value (1-5)", "cohens_d", 0.187,
       se=0.029, n=3900, direction=1,
       outcome_type="individual_creativity", notes="p<0.001"),
    _e("boussioux_etal_2024", 4, "Financial Value (HAI vs HC)",
       "Human-AI", "Human Crowd",
       "Financial Value (1-5)", "cohens_d", 0.146,
       se=0.033, n=3900, direction=1,
       outcome_type="individual_creativity", notes="p<0.001"),
    _e("boussioux_etal_2024", 5, "Overall Quality (HAI vs HC)",
       "Human-AI", "Human Crowd", "Quality (1-5)",
       "cohens_d", 0.108, se=0.032, n=3900, direction=1,
       outcome_type="individual_creativity", notes="p=0.002"),
    _e("boussioux_etal_2024", 6, "Top Novelty (HAI vs HC)",
       "Human-AI", "Human Crowd",
       "P(rating=5) for Novelty", "raw_mean", -0.079,
       se=0.012, n=3900, direction=-1,
       outcome_type="individual_creativity",
       notes="7.9pp less; humans dominate tail; p<0.001"),
    _e("boussioux_etal_2024", 7, "Top Quality (HAI vs HC)",
       "Human-AI", "Human Crowd",
       "P(rating=5) for Quality", "raw_mean", -0.008,
       se=0.012, n=3900, direction=0,
       outcome_type="individual_creativity", notes="ns"),
    _e("boussioux_etal_2024", 8, "Novelty — HAI Multiple Instance vs HC",
       "HAI Multiple Instance (independent search)",
       "Human Crowd", "Novelty (1-5)",
       "cohens_d", -0.256, se=0.039, direction=-1,
       outcome_type="homogenization",
       notes="-0.217 raw; AI converges to mean"),
    _e("boussioux_etal_2024", 9, "Novelty — HAI Single Instance vs HC",
       "HAI Single Instance (differentiated search)",
       "Human Crowd", "Novelty (1-5)",
       "cohens_d", -0.036, se=0.039, direction=0,
       outcome_type="individual_creativity",
       notes="Differentiation prompts eliminate gap; p=0.156"),
    _e("boussioux_etal_2024", 10, "Novelty — SI vs MI",
       "Single Instance", "Multiple Instance",
       "Novelty (1-5)", "cohens_d", 0.235, direction=1,
       outcome_type="diversity",
       notes="Differentiation prompts boost novelty; p<0.001"),
    _e("boussioux_etal_2024", 11, "Quality — SI vs MI",
       "Single Instance", "Multiple Instance",
       "Quality (1-5)", "cohens_d", 0.123, direction=1,
       outcome_type="individual_creativity", notes="p<0.001"),
    _e("boussioux_etal_2024", 12, "Strategic Viability — SI vs HC",
       "Single Instance", "Human Crowd",
       "Strategic Viability", "cohens_d", 0.123,
       se=0.041, direction=1, outcome_type="individual_creativity"),
    _e("boussioux_etal_2024", 13, "Quality — SI vs HC",
       "Single Instance", "Human Crowd", "Quality",
       "cohens_d", 0.170, se=0.036, direction=1,
       outcome_type="individual_creativity"),
    _e("boussioux_etal_2024", 14, "Top Novelty — MI vs HC",
       "Multiple Instance", "Human Crowd",
       "P(Top Novelty)", "raw_mean", -0.091,
       se=0.014, direction=-1, outcome_type="homogenization",
       notes="9.1pp less; tail novelty"),
    _e("boussioux_etal_2024", 15, "Top Novelty — SI vs HC",
       "Single Instance", "Human Crowd",
       "P(Top Novelty)", "raw_mean", -0.065,
       se=0.014, direction=-1, outcome_type="homogenization",
       notes="6.5pp less"),
    _e("boussioux_etal_2024", 16, "Top-decile Novelty (raw)",
       "HAI (MI or SI)", "HC top decile",
       "Novelty within top-decile solutions",
       "raw_mean", -0.40, direction=-1,
       outcome_type="homogenization",
       notes="HC 4.36 vs MI 3.90 vs SI 4.00; gap at the tail"),

    # ════════════════════════════════════════════════════════════════════════
    # Girotra et al (2023) — Ideas Are Dimes a Dozen
    # 14 outcomes. Mostly raw means (mixed-effects) + cosine + top-decile counts.
    # ════════════════════════════════════════════════════════════════════════
    _e("girotra_etal_2023", 1, "Quality — zero-shot GPT-4 vs human",
       "GPT-4 zero-shot", "Human (student)",
       "Avg purchase intent (Jameson-Bass)",
       "raw_mean", 0.059, ci_lo=0.031, ci_hi=0.088,
       n=400, direction=1, outcome_type="individual_creativity",
       notes="0.464 vs 0.404; t(246)=4.06, p<0.001"),
    _e("girotra_etal_2023", 2, "Quality — few-shot GPT-4 vs human",
       "GPT-4 few-shot", "Human", "Avg purchase intent",
       "raw_mean", 0.089, ci_lo=0.060, ci_hi=0.12, n=400,
       direction=1, outcome_type="individual_creativity", notes="p<0.001"),
    _e("girotra_etal_2023", 3, "Quality — few-shot vs zero-shot",
       "GPT-4 few-shot", "GPT-4 zero-shot", "Purchase intent",
       "raw_mean", 0.03, ci_lo=-0.01, ci_hi=0.06, n=200,
       direction=1, outcome_type="individual_creativity",
       notes="Few-shot edge; p=0.06"),
    _e("girotra_etal_2023", 4, "Pairwise cosine similarity (overall)",
       "GPT-4 (combined)", "Human",
       "Avg pairwise cosine (USE embeddings)",
       "pairwise_cosine", 0.422-0.221, direction=-1,
       outcome_type="homogenization",
       notes="Human 0.22 vs GPT-4 ~0.42; F=12340, η²=0.455"),
    _e("girotra_etal_2023", 5, "Fraction overlapping (cosine>0.8)",
       "GPT-4 zero/few-shot", "Human",
       "Fraction overlapping ideas",
       "other", 0.06-0.00, direction=-1,
       outcome_type="homogenization",
       notes="Human 0% vs zero 5% vs few-shot 7%; p<0.001"),
    _e("girotra_etal_2023", 6, "Opportunity space size (T)",
       "GPT-4 zero/few-shot", "Human",
       "Capture-recapture T estimate",
       "other", -700, direction=-1, outcome_type="diversity",
       notes="zero-shot T=966, few-shot T=680, humans=∞"),
    _e("girotra_etal_2023", 7, "MST mean edge distance",
       "GPT-4 zero/few-shot", "Human",
       "Mean MST edge length (512-dim)",
       "other", 0.32-0.53, direction=-1,
       outcome_type="homogenization",
       notes="Human 0.53 vs zero 0.33 vs few 0.30"),
    _e("girotra_etal_2023", 8, "Perceived novelty — zero-shot",
       "GPT-4 zero-shot", "Human",
       "Perceived novelty (Shibayama)",
       "raw_mean", -0.038, ci_lo=-0.066, ci_hi=-0.01, n=400,
       direction=-1, outcome_type="individual_creativity",
       notes="t(269)=-2.67, p=0.008"),
    _e("girotra_etal_2023", 9, "Perceived novelty — few-shot",
       "GPT-4 few-shot", "Human", "Perceived novelty",
       "raw_mean", -0.049, ci_lo=-0.078, ci_hi=-0.02, n=400,
       direction=-1, outcome_type="individual_creativity",
       notes="p<0.001"),
    _e("girotra_etal_2023", 10, "Top-decile concentration",
       "GPT-4 (combined)", "Human",
       "Share of top 40/400 ideas",
       "other", 35-5, n=400, direction=1,
       outcome_type="individual_creativity",
       notes="AI 35 (87.5%) vs Human 5 (12.5%); χ²=26, p<0.001"),
    _e("girotra_etal_2023", 11, "Top-5% concentration",
       "GPT-4", "Human", "Share of top 20/400",
       "other", 19-1, n=400, direction=1,
       outcome_type="individual_creativity",
       notes="AI 19 vs Human 1"),
    _e("girotra_etal_2023", 12, "Top-15% concentration",
       "GPT-4", "Human", "Share of top 60/400",
       "other", 49-11, n=400, direction=1,
       outcome_type="individual_creativity",
       notes="AI 49 vs Human 11"),
    _e("girotra_etal_2023", 13, "Quantile regression — 90th percentile",
       "GPT-4", "Human", "Quality at q=0.9",
       "other", 0.318, ci_lo=0.191, ci_hi=0.446, n=400,
       direction=1, outcome_type="individual_creativity",
       notes="q=0.8 also +0.445"),
    _e("girotra_etal_2023", 14, "Idea generation rate",
       "GPT-4 (with human)", "Human alone",
       "Ideas per 15 min", "other", 200-5, direction=1,
       outcome_type="idea_quantity", notes="~40:1 ratio"),
]


def main():
    import json
    from pathlib import Path
    from collections import Counter

    out = Path(r"C:\Users\greyes\Dropbox\Admin\website\ai-skill-atlas\src\creativity_estimates.json")
    out.write_text(json.dumps(ESTIMATES, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"WROTE {out} ({len(ESTIMATES)} estimates)")

    n_per_paper = Counter(e["paper_key"] for e in ESTIMATES)
    print("\nEstimates per paper:")
    for k, n in sorted(n_per_paper.items(), key=lambda kv: -kv[1]):
        print(f"  {n:>3} | {k}")

    by_type = Counter(e["outcome_type"] for e in ESTIMATES)
    print("\nBy outcome_type:")
    for t, n in sorted(by_type.items(), key=lambda kv: -kv[1]):
        print(f"  {n:>3} | {t}")

    by_metric = Counter(e["metric_type"] for e in ESTIMATES)
    print("\nBy metric_type:")
    for t, n in sorted(by_metric.items(), key=lambda kv: -kv[1]):
        print(f"  {n:>3} | {t}")

    by_direction = Counter(e["direction"] for e in ESTIMATES)
    print("\nBy direction:")
    print(f"  +1 (AI helps / heterogenizes): {by_direction[1]}")
    print(f"   0 (mixed / null):             {by_direction[0]}")
    print(f"  -1 (AI hurts / homogenizes):   {by_direction[-1]}")


if __name__ == "__main__":
    main()
